# Generated by Django 5.0.14 on 2026-08-15 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_type', models.CharField(choices=[('personal', 'Personal'), ('family', 'Family'), ('business', 'Business'), ('custom', 'Custom')], default='personal', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('icon', models.CharField(blank=True, default='wallet', max_length=32)),
                ('color', models.CharField(blank=True, default='#4F46E5', max_length=7)),
                ('is_default', models.BooleanField(default=False)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='families.family')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
