# Generated by Django 5.0.14 on 2026-08-15 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialprofile',
            index=models.Index(fields=['owner', 'profile_type'], name='profiles_fi_owner_i_64bec7_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner', 'name'), name='unique_profile_name_per_owner'),
        ),
    ]
