# Generated by Django 5.0.14 on 2026-08-15 08:31

import apps.common.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('bank_savings', 'Bank Savings'), ('bank_current', 'Bank Current'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('investment', 'Investment Account'), ('loan', 'Loan'), ('other', 'Other')], max_length=20)),
                ('institution', models.CharField(blank=True, default='', max_length=100)),
                ('last_four_digits', apps.common.fields.EncryptedTextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Must be exactly 4 digits.')])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('color', models.CharField(blank=True, default='#0EA5E9', max_length=7)),
                ('icon', models.CharField(blank=True, default='landmark', max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
