# Generated by Django 5.0.14 on 2026-08-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='profiles.financialprofile'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['profile', 'status'], name='accounts_ac_profile_e36df2_idx'),
        ),
    ]
