# Generated by Django 5.0.14 on 2026-08-15 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=10)),
                ('icon', models.CharField(blank=True, default='tag', max_length=32)),
                ('color', models.CharField(blank=True, default='#6B7280', max_length=7)),
                ('is_system_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('keyword', models.CharField(db_index=True, max_length=100)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower runs first.')),
            ],
            options={
                'ordering': ['priority', 'keyword'],
            },
        ),
    ]
