# Generated by Django 5.0.14 on 2026-08-15 08:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Income)'), ('debit', 'Debit (Expense)')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('transaction_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('merchant', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('netbanking', 'Net Banking'), ('cheque', 'Cheque'), ('auto_debit', 'Auto Debit'), ('other', 'Other')], default='', max_length=20)),
                ('reference_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('import', 'Bank Statement Import'), ('recurring', 'Recurring Transaction')], default='manual', max_length=20)),
                ('import_batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('duplicate_signature', models.CharField(db_index=True, editable=False, max_length=64)),
                ('version', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
